import type { ReactNode } from 'react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../services/api'
import type { Analysis, AnalysisSummary } from '../types'

function PageHeader({ index, eyebrow, title, description }: { index: string; eyebrow: string; title: string; description: string }) {
  return <section className="page-header"><div className="eyebrow"><span>{index}</span>{eyebrow}</div><h1>{title}</h1><p>{description}</p></section>
}
function EmptyPanel({ title, text, action }: { title: string; text: string; action?: ReactNode }) { return <div className="empty-panel"><span className="cross" aria-hidden="true">+</span><strong>{title}</strong><p>{text}</p>{action}</div> }
function ErrorNotice({ message }: { message: string }) { return <div className="error-notice" role="alert"><strong>REQUEST ERROR</strong><span>{message}</span></div> }

export function DashboardPage() {
  const [items, setItems] = useState<AnalysisSummary[]>([])
  const [health, setHealth] = useState('CHECKING')
  const [error, setError] = useState('')
  useEffect(() => { api.analyses().then(setItems).catch(e => setError(e.message)); api.health().then(() => setHealth('ONLINE')).catch(() => setHealth('OFFLINE')) }, [])
  const detections = items.reduce((sum, item) => sum + item.detection_count, 0)
  return <><PageHeader index="01" eyebrow="COMMAND CENTER" title="Shelf intelligence." description="Turn shelf imagery into traceable computer-vision observations with real detections and confidence scores." />{error && <ErrorNotice message={error} />}<section className="hero-grid"><article className="panel hero-panel"><div className="panel-label">VISION / CONNECTED</div><h2>See the shelf.<br /><span>Know the shelf.</span></h2><p>Upload a shelf image, run the backend vision pipeline, and inspect every returned detection instead of relying on placeholder analytics.</p><Link className="primary-button" to="/analyze">START ANALYSIS <span>↗</span></Link></article><div className="metric-stack"><article className="metric-card"><span>ANALYSES</span><strong>{items.length}</strong><small>Stored analysis records</small></article><article className="metric-card accent"><span>DETECTIONS</span><strong>{detections}</strong><small>Across loaded analyses</small></article><article className="metric-card"><span>API</span><strong>{health}</strong><small>FastAPI health endpoint</small></article></div></section><section className="section-block"><div className="section-heading"><div><span className="panel-label">RECENT / ANALYSIS LOG</span><h2>Recent analyses</h2></div><Link className="text-link" to="/history">VIEW HISTORY ↗</Link></div>{items.length ? <AnalysisTable items={items.slice(0, 5)} /> : <EmptyPanel title="NO ANALYSES RECORDED" text="Create an authenticated analysis to populate this workspace." action={<Link className="secondary-button" to="/settings">CONFIGURE ACCESS</Link>} />}</section></>
}

function Pipeline({ active }: { active: number }) { return <ol className="pipeline">{['Validate image', 'Preprocess with OpenCV', 'Run YOLO inference', 'Analyze detections', 'Store result'].map((step, index) => <li key={step} className={index < active ? 'done' : index === active ? 'current' : ''}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong><small>{index < active ? 'DONE' : index === active ? 'RUNNING' : 'WAITING'}</small></li>)}</ol> }

function AnalysisTable({ items }: { items: AnalysisSummary[] }) { return <div className="table-wrap"><table><thead><tr><th>IMAGE</th><th>STATUS</th><th>DETECTIONS</th><th>MODEL</th><th>CREATED</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.image_name}</td><td>{item.status}</td><td>{item.detection_count}</td><td>{item.model_name}</td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}</tbody></table></div> }

export function AnalyzePage() {
  const inputRef = useRef<HTMLInputElement>(null)
  const [analysis, setAnalysis] = useState<Analysis | null>(null)
  const [error, setError] = useState('')
  const [processing, setProcessing] = useState(false)
  const [dragging, setDragging] = useState(false)
  async function processFile(file?: File) { if (!file) return; setError(''); setAnalysis(null); setProcessing(true); try { setAnalysis(await api.createAnalysis(file)) } catch (e) { setError(e instanceof Error ? e.message : 'Analysis failed') } finally { setProcessing(false) } }
  return <><PageHeader index="02" eyebrow="ANALYZE / LIVE PIPELINE" title="Inspect a shelf." description="Submit one image for validated decoding, OpenCV preprocessing, YOLOX-Tiny inference, and authenticated persistence." />{error && <ErrorNotice message={error} />}<section className="analysis-workspace"><article className="panel upload-panel"><div className="panel-label">INPUT / IMAGE</div><div className={dragging ? 'upload-zone dragging' : 'upload-zone'} tabIndex={0} role="button" onClick={() => inputRef.current?.click()} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') inputRef.current?.click() }} onDragOver={e => { e.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); void processFile(e.dataTransfer.files[0]) }}><div className="scan-icon">⌁</div><h2>{processing ? 'PROCESSING…' : 'DROP IMAGE'}</h2><p>JPEG, PNG, or WebP. Maximum upload size is 10 MB.</p><button className="secondary-button" type="button" onClick={e => { e.stopPropagation(); inputRef.current?.click() }}>CHOOSE FILE</button><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e => void processFile(e.target.files?.[0])} /></div></article><aside className="panel status-panel"><div className="panel-label">PIPELINE / STATUS</div><Pipeline active={processing ? 2 : analysis ? 5 : 0} />{analysis && <div className="notice"><strong>ANALYSIS STORED</strong><p>{analysis.detection_count} generic COCO detections returned by {analysis.model_name}.</p></div>}</aside></section>{analysis && <section className="section-block"><div className="section-heading"><div><span className="panel-label">RESULT / {analysis.model_name}</span><h2>{analysis.image_name}</h2></div><span className="mono">{analysis.detection_count} DETECTIONS</span></div><div className="panel result-panel"><div className="result-image-placeholder"><span>IMAGE RESULT</span><small>Bounding-box data is available from the API. Visual overlay rendering remains tied to the existing result component.</small></div><div className="detection-list">{analysis.detections.map((detection, index) => <div className="detection-row" key={`${detection.class_name}-${index}`}><strong>{detection.class_name}</strong><span>{(detection.confidence * 100).toFixed(1)}%</span><small>{detection.box.x.toFixed(0)},{detection.box.y.toFixed(0)} · {detection.box.width.toFixed(0)}×{detection.box.height.toFixed(0)}</small></div>)}</div></div></section>}</>
}

export function HistoryPage() { const [items, setItems] = useState<AnalysisSummary[]>([]); const [error, setError] = useState(''); useEffect(() => { api.analyses().then(setItems).catch(e => setError(e.message)) }, []); return <><PageHeader index="03" eyebrow="HISTORY / TRACEABILITY" title="Analysis log." description="Every authenticated result is scoped to the signed-in user and loaded from the retail database schema." />{error && <ErrorNotice message={error} />}{items.length ? <AnalysisTable items={items} /> : <EmptyPanel title="NO HISTORY" text="No persisted analyses are available for this account yet." />}</> }

export function AnalyticsPage() { const [items, setItems] = useState<AnalysisSummary[]>([]); useEffect(() => { api.analyses().then(setItems).catch(() => setItems([])) }, []); const detections = items.reduce((sum, item) => sum + item.detection_count, 0); return <><PageHeader index="04" eyebrow="ANALYTICS / OBSERVATIONS" title="Measure what was seen." description="Aggregate persisted analysis observations without pretending generic COCO detections are retail SKU or stock recognition." /><div className="analytics-grid"><article className="panel"><span className="panel-label">ANALYSES</span><div className="big-zero">{items.length}</div><p>Authenticated analysis records returned from the retail schema.</p></article><article className="panel"><span className="panel-label">DETECTIONS</span><div className="big-zero">{detections}</div><p>Generic object detections produced by YOLOX-Tiny.</p></article></div><div className="signal-line"><span /><span /><span /><span /></div></> }

export function SettingsPage() { const navigate = useNavigate(); return <><PageHeader index="05" eyebrow="SETTINGS / ACCESS" title="System settings." description="Authentication and infrastructure configuration stay outside source control. This client only receives publishable Supabase configuration." /><section className="panel settings-panel"><div className="setting-row"><div><strong>Authentication</strong><span>Supabase Auth access tokens</span></div><span className="mono">ENABLED</span></div><div className="setting-row"><div><strong>Database namespace</strong><span>retail_shelf_intelligence</span></div><span className="mono">ISOLATED</span></div><div className="setting-row"><div><strong>Model</strong><span>YOLOX-Tiny / COCO</span></div><span className="mono">GENERIC</span></div><div className="setting-row"><div><strong>Upload guard</strong><span>10 MB application limit</span></div><span className="mono">ACTIVE</span></div><div className="setting-row"><div><strong>Session</strong><span>End the current authenticated session</span></div><button className="secondary-button" type="button" onClick={() => { sessionStorage.removeItem('retail_vision_access_token'); navigate('/login', { replace: true }) }}>SIGN OUT</button></div></section></> }
